---
- hosts: prod
  become: yes
  vars_files:
    - ../vars/ssh.yml
  tasks:
    - name: Restart Tomcat
      ansible.builtin.shell: pwd
      args:
        chdir: "{{ scripts_folder }}"
	
    - name: Restart Tomcat
      ansible.builtin.shell: /usr/local/bin/docker-compose down subtitles-tomcat && /usr/local/bin/docker-compose up -d subtitles-tomcat
      args:
        chdir: "{{ scripts_folder }}"