package com.subtitlescorrector.domain;

public enum VariablesEnum {

	
	KAFKA_CLIENT_KEYSTORE_PASSWORD("SECRET_KAFKA_CLIENT_TLS_KEY_PASSWORD"),
	KAFKA_CLIENT_KEYSTORE_LOCATION("SECRET_KAFKA_CLIENT_TLS_KEYSTORE_LOCATION"),
	KAFKA_CLIENT_KEY_PASSWORD("SECRET_KAFKA_CLIENT_TLS_KEYSTORE_PASSWORD"),
	KAFKA_CLIENT_TRUSTSTORE_PASSWORD("SECRET_KAFKA_CLIENT_TLS_TRUSTSTORE_PASSWORD"),
	KAFKA_CLIENT_TRUSTSTORE_LOCATION("SECRET_KAFKA_CLIENT_TLS_TRUSTSTORE_LOCATION"),
	
	KAFKA_SCHEMA_REGISTRY_URL("SECRET_KAFKA_SCHEMA_REGISTRY_URL"),
	KAFKA_BOOTSTRAP_SERVERS("SECRET_KAFKA_BOOTSTRAP_SERVERS"),
	
	KAFKA_SERVER_KEYSTORE_PASSWORD("SECRET_KAFKA_SERVER_TLS_KEYSTORE_PASSWORD"),
	KAFKA_SERVER_KEYSTORE_LOCATION("SECRET_KAFKA_SERVER_TLS_KEYSTORE_LOCATION"),
	KAFKA_SERVER_KEY_PASSWORD("SECRET_KAFKA_SERVER_TLS_KEY_PASSWORD"),
	KAFKA_SERVER_TRUSTSTORE_PASSWORD("SECRET_KAFKA_SERVER_TLS_TRUSTSTORE_PASSWORD"),
	KAFKA_SERVER_TRUSTSTORE_LOCATION("SECRET_KAFKA_SERVER_TLS_TRUSTSTORE_LOCATION"),
	APPLICATION_ENVIRONMENT("APP_ENVIRONMENT"),
	TOMCAT_KEYSTORE_PASSWORD("TOMCAT_KEYSTORE_PASSWORD"),
	
	MAIL_SENDER_PASSWORD("MAIL_SENDER_PASSWORD"),
	EMAIL_ADDRESS_FOR_SENDING("EMAIL_ADDRESS_FOR_SENDING"),
	ADMIN_EMAIL_ADDRESS("ADMIN_EMAIL_ADDRESS");
	
	
	private String name;
	
	VariablesEnum(String name) {
		this.name = name;
	}
	
	public String getName() {
		return name;
	}
	
	
}
