name: Certificates check

on:
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch:

jobs:
  check-certs:
    name: Check tls certificates and update if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ansible
        uses: ./.github/actions/ansible-setup

      - name: Check using Ansible
        run: |
          cd $GITHUB_WORKSPACE/ansible
          ansible-playbook -i $GITHUB_WORKSPACE/ansible/inventory/hosts $GITHUB_WORKSPACE/ansible/playbooks/check_tls_certificates.yml --vault-password-file ~/ansible-vault/password
          