name: Certificates check

on:
  schedule:
    - cron: 0 0 * * MON
  workflow_dispatch:

jobs:
  check-certs:
    name: Check tls certificates and update if needed
    runs-on: ubuntu-latest
    steps:

      - name: Install Compatible Ansible
        run: |
          python -m pip install --upgrade pip
          # 2.14.x is the last version that fully supports the older
          # Python 3.7/3.8 environments
          pip install "ansible-core==2.14.11" ansible

      - name: Check using Ansible
        run: ansible-playbook -i $GITHUB_WORKSPACE/ansible/inventory/hosts check_tls_certificates.yml
