name: Deploy release

on:
  workflow_dispatch:    
    inputs:
      tag:
        description: 'Tag to run this workflow for'
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for tags + release plugin
          ref: ${{ github.event.inputs.tag }}

      - name: Extract version
        id: version # Id to reference version from other steps
        run: |
          VERSION=${{ github.event.inputs.tag }} # Set version from workflow manual input to a variable
          VERSION=${VERSION#subtitlescorrector-} # Remove subtitlescorrector- prefix
          echo "version=$VERSION" >> $GITHUB_OUTPUT # Write variable to GITHUB_OUTPUT so other steps can access it

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::841162706718:role/subtitles-corrector-ecr-role
          aws-region: eu-north-1

      - name: Setup frontend env variables
        run: |
          # Overwrite the .env file and add environment variables for vue
          cat > "$GITHUB_WORKSPACE"/src/main/resources/static/views/frontend-vue/.env <<EOL
          VUE_APP_ENVIRONMENT=prod
          EOL

      - name: "Setup Node 16" 
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Build frontend - Vue and Bulma
        working-directory: src/main/resources/static/views/frontend-vue
        run: |
          echo "Building front-end files..."
          npm ci
          npm run build-bulma
          npm run build
          cp -r dist/* ../

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 \
          | docker login \
            --username AWS \
            --password-stdin 841162706718.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t subtitles-corrector-image:${{ steps.version.outputs.version }} . # Will use Dockerfile located at project root

      - name: Tag image
        run: |
          docker tag subtitles-corrector-image:${{ steps.version.outputs.version }} \
          841162706718.dkr.ecr.eu-north-1.amazonaws.com/subtitles/subtitles-corrector:${{ steps.version.outputs.version }}

      - name: Push image
        run: |
          docker push 841162706718.dkr.ecr.eu-north-1.amazonaws.com/subtitles/subtitles-corrector:${{ steps.version.outputs.version }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
	
    steps:
      - name: Set up Ansible
        uses: actions/ansible-setup
		
      - name: Deployment
        if: success()
        run: |
          echo "Ansible deployment start..."
          cd $GITHUB_WORKSPACE/ansible
          ansible-playbook -i inventory/hosts \
          playbooks/deploy.yml --extra-vars app_version=${{ steps.version.outputs.version }} --vault-password-file ~/ansible-vault/password
 
  restart-tomcat:
    name: Restart Tomcat
    runs-on: ubuntu-latest
	
    steps:
      - name: Set up Ansible
        uses: actions/ansible-setup
		
      - name: Restart Tomcat
        run: |
         cd $GITHUB_WORKSPACE/ansible
         ansible-playbook -i inventory/hosts playbooks/restart-tomcat.yml
