name: Restart Tomcat

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  restart-tomcat:
    name: Restart Tomcat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Ansible
        uses: ./.github/actions/ansible-setup
        with: 
          ssh_private_key: ${{ secrets.ANSIBLE_USER_SSH_PRIV_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Restart Tomcat
        run: |
         cd $GITHUB_WORKSPACE/ansible
         ansible-playbook -i inventory/hosts -vvvv playbooks/restart-tomcat.yml
